# Generated by Django 3.1.3 on 2020-12-12 22:26

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('alt', models.TextField(null=True)),
                ('image', models.ImageField(default='posts/default.jpg', upload_to=images.models.user_directory_path)),
                ('slug', models.SlugField(max_length=250, unique_for_date='created_at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
