# Generated by Django 3.1.3 on 2020-11-24 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('admin', 'Admin'), ('member', 'Member')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen_app.room')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
