# Generated by Django 3.1.3 on 2020-11-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0003_auto_20201124_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommembers',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
