# Generated by Django 3.1.3 on 2020-11-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0005_auto_20201129_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommembers',
            old_name='roomID',
            new_name='room',
        ),
    ]
