# Generated by Django 3.1.3 on 2020-12-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0010_subtasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='deadline',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
