# Generated by Django 3.1.3 on 2020-12-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0013_events_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
