# Generated by Django 3.1.3 on 2020-12-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0016_remove_posts_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitchen_app.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='room',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='kitchen_app.room'),
            preserve_default=False,
        ),
    ]
