# Generated by Django 3.1.3 on 2020-12-05 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0018_auto_20201205_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='room',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='kitchen_app.room'),
            preserve_default=False,
        ),
    ]
