# Generated by Django 3.1.3 on 2020-12-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0020_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='deadline',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
