# Generated by Django 3.1.3 on 2020-12-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0022_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
