# Generated by Django 3.1.3 on 2020-12-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0025_auto_20201212_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='backgroundImage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
