# Generated by Django 3.1.3 on 2020-12-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0026_room_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mobilePayBox',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
