# Generated by Django 3.1.3 on 2020-12-14 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0031_chat_chatmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmembers',
            name='room',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='kitchen_app.room'),
            preserve_default=False,
        ),
    ]
