# Generated by Django 3.1.3 on 2020-12-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0032_chatmembers_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmembers',
            name='room',
        ),
        migrations.RemoveField(
            model_name='chatmembers',
            name='user',
        ),
        migrations.AddField(
            model_name='chatmembers',
            name='member',
            field=models.ForeignKey(default=58, on_delete=django.db.models.deletion.CASCADE, to='kitchen_app.roommembers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='dorm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='fund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
