# Generated by Django 3.1.3 on 2020-12-14 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kitchen_app', '0033_auto_20201214_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmembers',
            name='member',
        ),
        migrations.AddField(
            model_name='chatmembers',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kitchen_app.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmembers',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
