# Generated by Django 3.1.3 on 2020-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0036_auto_20201214_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='fund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='mobilePayBox',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
