# Generated by Django 3.1.3 on 2021-01-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_app', '0039_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
