# Generated by Django 3.1.3 on 2021-01-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresetrequest',
            old_name='secret',
            new_name='token',
        ),
    ]
