# Generated by Django 3.1.3 on 2021-01-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_signupcofirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpCofirmation',
        ),
    ]
